# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST http://localhost:8080/api/spots?country=Spain&windProbability=97
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "token": "6f8ec628-8772-4fd8-8dcf"
}

###

POST http://localhost:8080/api/spots?country=234SD
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "token": "6f8ec628-8772-4fd8-8dcf-91b9b134f758"
}

###

POST http://localhost:8080/api/spots?windProbability=-1
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "token": "6f8ec628-8772-4fd8-8dcf-91b9b134f758"
}

###

###

POST http://localhost:8080/api/spots/countries
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "token": "6f8ec628-8772-4fd8-8dcf-91b9b134f758"
}

###
POST http://localhost:8080/api/spots/5
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "token": "6f8ec628-8772-4fd8-8dcf-91b9b134f758"
}

###